# Change these first
owner: PBOwner # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Fenrus
    url: https://dash.havenhost.icu
  - name: Innova Control Panel
    url: https://innova.havenhost.icu
  - name: Innova, Inc Links
    url: https://links.havenhost.icu
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: Innova Ping
    url: 195.58.58.43
    port: 8710
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Innova, Inc Status Updates
  introTitle: "Innova, Inc Status Updates. Where all of Innova, Inc's products statuses have everything needed. Powered by GitHub, created by Rosie
  introMessage: Innova, Inc Status Updates. Ensure you check the statuses often if you ever notice anything weird
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
